-- 0001_baseline.sql
--
-- Baseline schema for VlogMap, captured from the live production database
-- (Neon project quiet-hill-98016369, branch br-aged-base-adbousc5) on 2026-06-17.
--
-- This file is the SINGLE SOURCE OF TRUTH for the database schema. It is fully
-- idempotent (every statement is guarded with IF NOT EXISTS / inline constraints
-- inside CREATE TABLE), so running it against the existing production database is
-- a safe no-op that simply "baselines" it. Against a fresh database it builds the
-- complete schema.
--
-- DO NOT edit this file to make schema changes. Add a new numbered migration
-- (0002_*.sql, 0003_*.sql, ...) and apply it with `npm run db:migrate`. Never
-- mutate the schema with ad-hoc ALTERs in application code again — that is what
-- caused db.ts and production to drift apart.

-- ---------------------------------------------------------------------------
-- creators — a YouTube channel. One creator has many markers.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS creators (
  id          SERIAL PRIMARY KEY,
  name        TEXT NOT NULL UNIQUE,
  channel_url TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- locations — real-world places forming a 2-tier tree (city -> landmark).
-- parent_location_id self-references this table; cities have a NULL parent.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS locations (
  id                 VARCHAR(100) PRIMARY KEY,
  latitude           DOUBLE PRECISION NOT NULL,
  longitude          DOUBLE PRECISION NOT NULL,
  city               TEXT,
  name               TEXT,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  district           TEXT,
  country            TEXT,
  type               VARCHAR(20),                  -- 'city' | 'landmark'
  parent_location_id VARCHAR(100) REFERENCES locations(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_locations_coords ON locations (latitude, longitude);
CREATE INDEX IF NOT EXISTS idx_locations_parent ON locations (parent_location_id);

-- ---------------------------------------------------------------------------
-- explorer_markers — a "check-in": one creator filming at one location.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS explorer_markers (
  id                 SERIAL PRIMARY KEY,
  title              TEXT NOT NULL,
  video_url          TEXT,
  description        TEXT,
  latitude           DOUBLE PRECISION NOT NULL,
  longitude          DOUBLE PRECISION NOT NULL,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  video_published_at TIMESTAMPTZ,
  city               TEXT,
  screenshot_url     TEXT,
  summary            TEXT,
  location_id        VARCHAR(100) CONSTRAINT fk_location_id REFERENCES locations(id) ON DELETE SET NULL,
  district           TEXT,
  country            TEXT,
  timestamp          VARCHAR(8),
  creator_id         INTEGER NOT NULL CONSTRAINT fk_creator_id REFERENCES creators(id),

  -- DEPRECATED: legacy columns from the pre-`locations` design. Not written or
  -- read by application code; retained only to match production exactly. Slated
  -- for removal in a future migration (schema cleanup task).
  type           VARCHAR(20),
  parent_city_id INTEGER CONSTRAINT fk_parent_city_id REFERENCES explorer_markers(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_markers_creator_id  ON explorer_markers (creator_id);
CREATE INDEX IF NOT EXISTS idx_markers_location_id ON explorer_markers (location_id);
